name: Verify

permissions:
  contents: write
  packages: write

on:
  push:
    branches: [ main ]

jobs:
  test-and-create-image:
    runs-on: ubuntu-latest
    steps:
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
         node-version: 'lts/*'
         cache: 'npm' # Set this to npm, yarn or pnpm.  
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.5,cargo-deny@0.13,just@1,hurl@4,cargo-edit@0.12
      - run: just verify
