name: Verify

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
         node-version: 'lts/*'
         cache: 'npm' # Set this to npm, yarn or pnpm.  
      - name: Install dependencies ubuntu only
         # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
           sudo apt-get update
           sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev
 
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
 
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
         workspaces: './src-tauri -> target'
 
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.5,cargo-deny@0.13,just@1,hurl@4,cargo-edit@0.12
      - run: just verify
